### ISSUE TITLE
Would you be okay with me making a Hugo Port of this theme?

### ISSUE THREAD

**Issue by GeorgeWL** [lukas-h/material-theme#13]
[Hugo](//gohugo.io) is the StaticGen currently in second place to Jekyll in number of active users.

I'm currently using it and I love your theme, so wondered if you'd be okay with me porting it?

For personal use, but I would like to have it show in the [Themes Showcase](//themes.gohugo.io) with Copyright pointing back to this theme. With your permission.

It's more structured than Jekyll (with strongly defined trees of heirarchy for layouts and part files) but otherwise rather similar except for different syntax.

**Comment by lukas-h** [comment]
Hugo is really cool, would be nice to have this theme ported on Hugo.

**Comment by GeorgeWL** [comment]
and the Theme Showcase thing?

**Comment by lukas-h** [comment]
definitely a nice thing.
Please ask if I can help with something.

**Comment by GeorgeWL** [comment]
coolio.

Well, I'm not gonna jump straight to it, but I think I'll start with just forking this theme then working from there.

**Comment by lf-araujo** [comment]
Hey @GeorgeWL did you manage to port it?

**Comment by GeorgeWL** [comment]
ha, no, sorry, got a new job and forgot all about it @lf-araujo

**Comment by qazip** [comment]
I would also like a port of this theme to Hugo. Sadly, I lack the expertise to do so..

**Comment by lukas-h** [comment]
I will do a major update of this theme someday.. (with SASS & many improvements)
And for that matter, I create a Hugo port. I set that on the TODO list..

**Comment by lf-araujo** [comment]
Hi @lukas-h , I use your theme for a scientific blog. I publish some programming notes and links to my papers, book and conventions I organize. 

Your theme is excellent as it is, having it in Hugo would be fantastic, as I will then be able to blog directly from R and RStudio between my analyses.

I must say that the ability to create a toc in the beginning of the post has been very useful to my use case, also consider giving the users a couple of font options if possible. 

Finally, in case you have time in your life, for a scientist it would be perfect to have BibBase incorporated into the theme. Bibbase is a way of automatically creating the list of publication to one's personal website, you can learn about it in: https://bibbase.org/ and https://bibbase.github.io/

All the best,

lf

**Comment by lukas-h** [comment]
(outdated)
