### ISSUE TITLE
Increase paragraph's width

### ISSUE THREAD

**Issue by qazip** [lukas-h/material-theme#15]
Hello,

I'm testing our theme and by default, I find the width of the text to be too narrow (margins are too big). What would I need to change in order to increase the width (decrease the margins)?

Sorry for asking such an introductory question but I've never handled these kind of files.

**Comment by lukas-h** [comment]
You can change that in your CSS files and pull requests are appreciated.
If I find time I update the theme from ground up.. (I described more about updates at Issue #13)

**Comment by qazip** [comment]
Ya, would that be in main.css? I couldn't find anything that changed the left/right width/margins..

**Comment by lukas-h** [comment]
hmm not sure. I think it’s in the material framework CSS - that file is minified.. Therefore I need to update the theme with SASS, so anyone can find things easily
