### ISSUE TITLE
Dark version with a few other changes

### ISSUE THREAD

**Issue by miguelmf** [lukas-h/material-theme#17]
Hey Lukas,

I've cloned your repo and did some changes to my liking. I've hosted the repo here: https://github.com/miguelmf/material_theme_jekyll. You can see there the changes I made. They are pretty minimal.

I did not do pullrequests as my changes are pretty much non-optional, that is, there's no option in the _config, it's just a straight change in the codebase.

If you're not ok with this, please let me know and I will take it down.

**Comment by lukas-h** [comment]
Looks nice! I will add it to the readme

**Comment by miguelmf** [comment]
@lukas-h, thank you. I've also added a search function (using https://github.com/christian-fei/Simple-Jekyll-Search). You can see a "demo" of it on my page miguelmf.com.

I'll close this issue, no need to keep it open. Thank you for this amazing theme!

**Comment by lukas-h** [comment]
Thanks for your improvements and for letting me know :+1:
